from __future__ import annotations

from typing import Any


SUPPORTED_LANGUAGES = ("vi", "en")
DEFAULT_LANGUAGE = "vi"


TEXT: dict[str, dict[str, Any]] = {
    "vi": {
        "app_title": "Tải gió ASCE",
        "app_description": "Công cụ tính tải gió ASCE với giao diện kỹ thuật rõ ràng, kết quả minh bạch và báo cáo chuyên nghiệp.",
        "hero_eyebrow": "Không gian tính toán tải gió",
        "hero_parity_title": "Độ tin cậy",
        "hero_parity_value": "Đã kiểm chứng",
        "hero_parity_note": "Kết quả nhất quán và sẵn sàng cho workflow kỹ thuật",
        "hero_flow_title": "Quy trình làm việc",
        "hero_flow_value": "Nhập liệu, kiểm tra, xuất báo cáo",
        "hero_flow_note": "Dùng trực tiếp trong workflow thiết kế và lập hồ sơ",
        "input_workspace": "Khu vực nhập liệu",
        "project_inputs": "Thông số đầu vào",
        "load_sample": "Nạp mẫu",
        "reset": "Đặt lại",
        "import_json": "Nhập JSON",
        "export_input": "Xuất input",
        "export_result": "Xuất kết quả",
        "export_html": "Xuất HTML",
        "export_markdown": "Xuất Markdown",
        "export_pdf": "Xuất PDF",
        "copy_summary": "Copy tóm tắt",
        "copy_inputs": "Copy bảng input",
        "copy_breakdown": "Copy diễn giải tính",
        "copy_results": "Copy kết quả cuối",
        "run_calculation": "Chạy tính toán",
        "result_overview": "Tổng quan kết quả",
        "calculation_output": "Kết quả tính toán",
        "pressure_results": "Kết quả áp lực",
        "case_tables": "Bảng tải trọng",
        "audit_trail": "Dấu vết kiểm tra",
        "calculation_breakdown": "Diễn giải tính toán",
        "review_context": "Bối cảnh kiểm tra",
        "assumptions_notes": "Giả định / ghi chú",
        "no_calculation": "Chưa có lần tính nào",
        "run_to_populate": "Chạy tính toán để hiển thị các chỉ số chính, giá trị trung gian và bảng áp lực theo vùng.",
        "tables_placeholder": "Bảng Case A và Case B sẽ xuất hiện ở đây sau khi dữ liệu hợp lệ.",
        "breakdown_placeholder": "Phần mềm sẽ diễn giải các bước tính chính sau khi có kết quả.",
        "notes_placeholder": "Các giả định và lưu ý triển khai sẽ hiển thị tại đây.",
        "status_success": "Tính toán hoàn tất.",
        "status_imported": "Đã nhập dữ liệu đầu vào.",
        "status_sample_loaded": "Đã nạp bộ dữ liệu mẫu.",
        "status_invalid_json": "Tệp nhập không phải JSON hợp lệ.",
        "status_backend_error": "Không tải được cấu hình từ backend.",
        "status_validation": "Hãy kiểm tra các ô đang được tô lỗi.",
        "status_copy_success": "Đã copy vào clipboard.",
        "status_copy_fail": "Không copy được. Trình duyệt từ chối quyền clipboard.",
        "report_title": "Báo cáo tính toán tải gió ASCE",
        "report_subtitle": "Báo cáo này được sinh trực tiếp từ calculation engine của phần mềm.",
        "title_project_info": "Thông tin công trình",
        "title_calc_summary": "Tóm tắt tính toán",
        "title_design_criteria": "Tiêu chuẩn và tiêu chí thiết kế",
        "title_input_parameters": "Thông số đầu vào",
        "title_assumptions": "Giả định",
        "title_intermediate": "Giá trị trung gian",
        "title_final_results": "Kết quả cuối cùng",
        "title_notes": "Ghi chú / giới hạn",
        "title_warnings": "Cảnh báo",
        "title_copy_blocks": "Các khối nội dung copy-ready",
        "summary_narrative": "Dựa trên thông số gió, hệ số nội áp và các giá trị tra bảng tương ứng, áp lực vận tốc thiết kế được xác định và tổ hợp thành các áp lực vùng Case A và Case B phục vụ kiểm tra khung chính và đầu hồi.",
        "design_criteria_text": "Thiết kế sử dụng các công thức chuyển đổi vận tốc gió theo QCVN và ASCE, nội suy hệ số Kz và GCpf theo bảng tham chiếu nội bộ, và tổ hợp nội áp GCpi theo kiểu bao che công trình.",
        "report_not_applicable": "Không áp dụng",
        "warnings_none": "Không có cảnh báo nổi bật cho bộ dữ liệu hiện tại.",
        "last_run": "Lần chạy gần nhất",
        "metric_design_speed": "Vận tốc gió thiết kế",
        "metric_qz": "Áp lực vận tốc qz",
        "metric_roof_angle": "Góc mái",
        "metric_mean_roof_height": "Cao độ giữa mái",
        "metric_kz": "Hệ số Kz",
        "metric_gcpi_pos": "GCpi dương",
        "detail_design_speed": "Vận tốc gió thiết kế dùng cho tổ hợp áp lực",
        "detail_qz": "Áp lực vận tốc dùng cho các vùng áp lực",
        "detail_roof_angle": "Góc mái suy ra từ độ dốc nhập vào",
        "detail_mean_roof_height": "Cao độ giữa mái phục vụ tra hệ số",
        "detail_kz": "Nội suy từ bảng địa hình",
        "detail_gcpi_pos": "Hệ số nội áp dương đang xét",
        "breakdown_formula": "Biểu thức",
        "breakdown_note": "Giải thích",
        "case_a_title": "Case A: gió tác dụng lên tường bên",
        "case_b_title": "Case B: gió tác dụng lên đầu hồi",
        "line_load_title": "Tóm tắt line load theo vùng",
        "intermediate_title": "Các giá trị trung gian chính",
        "copy_block_design": "Tiêu chuẩn thiết kế",
        "copy_block_inputs": "Bảng đầu vào",
        "copy_block_breakdown": "Trình tự tính",
        "copy_block_results": "Kết quả cuối",
        "copy_block_notes": "Ghi chú",
        "language_label": "Ngôn ngữ",
        "language_vi": "Tiếng Việt",
        "language_en": "English",
        "project_name": "Tên dự án",
        "project_reference": "Mã tham chiếu",
        "generated_at": "Thời điểm sinh báo cáo",
        "unit_m": "m",
        "unit_years": "năm",
        "unit_percent": "%",
        "unit_pressure": "kN/m²",
        "unit_speed": "m/s",
        "unit_speed_kph": "km/h",
        "unit_speed_mph": "mph",
        "formula_substitute": "Thay số",
        "formula_result": "Kết quả",
    },
    "en": {
        "app_title": "Win Load ASCE",
        "app_description": "ASCE wind load tool with structured engineering inputs, transparent outputs, and professional report export.",
        "hero_eyebrow": "Wind engineering workspace",
        "hero_parity_title": "Workbook parity",
        "hero_parity_value": "Validated",
        "hero_parity_note": "Consistent results ready for engineering workflow",
        "hero_flow_title": "Workflow",
        "hero_flow_value": "Input, review, export",
        "hero_flow_note": "Use it directly for design checks and calculation reporting",
        "input_workspace": "Input workspace",
        "project_inputs": "Project inputs",
        "load_sample": "Load sample",
        "reset": "Reset",
        "import_json": "Import JSON",
        "export_input": "Export input",
        "export_result": "Export result",
        "export_html": "Export HTML",
        "export_markdown": "Export Markdown",
        "export_pdf": "Export PDF",
        "copy_summary": "Copy summary",
        "copy_inputs": "Copy input table",
        "copy_breakdown": "Copy breakdown",
        "copy_results": "Copy final results",
        "run_calculation": "Run calculation",
        "result_overview": "Result overview",
        "calculation_output": "Calculation output",
        "pressure_results": "Pressure results",
        "case_tables": "Case tables",
        "audit_trail": "Audit trail",
        "calculation_breakdown": "Calculation breakdown",
        "review_context": "Review context",
        "assumptions_notes": "Assumptions / notes",
        "no_calculation": "No calculation yet",
        "run_to_populate": "Run a calculation to populate headline metrics, intermediate values, and zone pressures.",
        "tables_placeholder": "Case A and Case B tables will appear here after validation passes.",
        "breakdown_placeholder": "The app exposes the main calculation steps once results are available.",
        "notes_placeholder": "Implementation assumptions and notes will be listed here.",
        "status_success": "Calculation completed successfully.",
        "status_imported": "Input data imported.",
        "status_sample_loaded": "Sample input loaded.",
        "status_invalid_json": "Imported file is not valid JSON.",
        "status_backend_error": "App failed to load configuration from the backend.",
        "status_validation": "Review the highlighted fields before recalculating.",
        "status_copy_success": "Copied to clipboard.",
        "status_copy_fail": "Unable to copy. Browser denied clipboard access.",
        "report_title": "ASCE Wind Load Calculation Report",
        "report_subtitle": "This report is generated directly from the validated calculation engine.",
        "title_project_info": "Project information",
        "title_calc_summary": "Calculation summary",
        "title_design_criteria": "Design criteria and code references",
        "title_input_parameters": "Input parameters",
        "title_assumptions": "Assumptions",
        "title_intermediate": "Intermediate calculations",
        "title_final_results": "Final results",
        "title_notes": "Notes / limitations",
        "title_warnings": "Warnings",
        "title_copy_blocks": "Copy-ready report blocks",
        "summary_narrative": "Based on the specified wind parameters, internal pressure coefficients, and table-derived factors, the design velocity pressure is established and combined into Case A and Case B zone pressures for frame and gable checks.",
        "design_criteria_text": "The design applies wind speed conversion per QCVN and ASCE, interpolation of Kz and GCpf from internal reference tables, and GCpi assignment based on enclosure classification.",
        "report_not_applicable": "Not applicable",
        "warnings_none": "No significant warnings are triggered for the current dataset.",
        "last_run": "Last run",
        "metric_design_speed": "Design speed",
        "metric_qz": "Velocity pressure qz",
        "metric_roof_angle": "Roof angle",
        "metric_mean_roof_height": "Mean roof height",
        "metric_kz": "Kz factor",
        "metric_gcpi_pos": "Positive GCpi",
        "detail_design_speed": "Design wind speed used for pressure combinations",
        "detail_qz": "Velocity pressure used across pressure zones",
        "detail_roof_angle": "Roof angle derived from user-entered slope",
        "detail_mean_roof_height": "Mean roof height used for coefficient lookup",
        "detail_kz": "Interpolated from exposure table",
        "detail_gcpi_pos": "Positive internal pressure coefficient",
        "breakdown_formula": "Expression",
        "breakdown_note": "Commentary",
        "case_a_title": "Case A: wind acting on side wall",
        "case_b_title": "Case B: wind acting on gable end",
        "line_load_title": "Workbook line-load labels",
        "intermediate_title": "Key intermediate values",
        "copy_block_design": "Design criteria",
        "copy_block_inputs": "Input summary",
        "copy_block_breakdown": "Calculation procedure",
        "copy_block_results": "Final results",
        "copy_block_notes": "Notes",
        "language_label": "Language",
        "language_vi": "Tiếng Việt",
        "language_en": "English",
        "project_name": "Project name",
        "project_reference": "Project reference",
        "generated_at": "Generated at",
        "unit_m": "m",
        "unit_years": "years",
        "unit_percent": "%",
        "unit_pressure": "kN/m²",
        "unit_speed": "m/s",
        "unit_speed_kph": "km/h",
        "unit_speed_mph": "mph",
        "formula_substitute": "Substitution",
        "formula_result": "Result",
    },
}


def get_text(lang: str) -> dict[str, Any]:
    return TEXT.get(lang, TEXT[DEFAULT_LANGUAGE])
